# basic-ass-creator.ps1
# Script PowerShell tạo phụ đề ASS đẹp mắt từ file JSON của Whisper với hiệu ứng highlight từng từ

# ------------ CẤU HỆNH CHUNG ------------
# Biến toàn cục dùng cho toàn bộ script
$script:ampersand = [char]38 # Ký tự '&'
$script:backslash = [char]92 # Ký tự '\'
$script:defaultColor = "FFFFFF" # Màu chữ mặc định (định dạng: bbggrr)
$script:highlightColor = "0CF4FF" # Màu highlight (định dạng: bbggrr)
$script:outlineColor = "000000" # Màu viền
$script:shadowColor = "000000" # Màu bóng đổ
$script:titleText = "Mèo 10 chân hút vape" # Văn bản tiêu đề
$script:titleColor1 = "00FFFF" # Màu gradient 1 cho title (định dạng: bbggrr)
$script:titleColor2 = "FF00FF" # Màu gradient 2 cho title (định dạng: bbggrr)
$script:titleDuration = 7.0 # Thời gian hiển thị title (giây)
$script:minWordCount = 3 # Số từ tối thiểu cho một phụ đề
$script:titleFont = "Arial" # Font chữ cho tiêu đề - thay đổi sang Arial để tương thích tốt hơn
$script:titleFontSize = 72 # Kích thước font cho tiêu đề
$script:titleBgOpacity = "A0" # Độ trong suốt cho nền title (00-FF)
$script:titleEffect = "modern" # Kiểu hiệu ứng cho title: "modern", "minimal", "3d"
$script:useTitleLayers = $true # Sử dụng layer dương thay vì layer âm
$script:maxCharsPerLine = 35 # Tăng số ký tự tối đa trên mỗi dòng để tránh cắt mất nội dung
$script:maxSubtitleLines = 2 # Số dòng tối đa cho phụ đề

# ------------ CÁC HÀM XỬ LÝ CƠ BẢN ------------
# Hàm thêm số 0 vào đầu
function PadZero {
    param (
        [int]$num,
        [int]$length = 2
    )
    
    return $num.ToString().PadLeft($length, '0')
}

# Hàm chuyển đổi số giây thành định dạng thời gian ASS (H:MM:SS.cs)
function FormatAssTime {
    param (
        [double]$seconds
    )
    
    $totalCentiseconds = [Math]::Floor($seconds * 100)
    $cs = $totalCentiseconds % 100
    $totalSeconds = [Math]::Floor($totalCentiseconds / 100)
    $s = $totalSeconds % 60
    $totalMinutes = [Math]::Floor($totalSeconds / 60)
    $m = $totalMinutes % 60
    $h = [Math]::Floor($totalMinutes / 60)
    
    return "${h}:$(PadZero $m):$(PadZero $s).$(PadZero $cs)"
}

# ------------ TẠO NỘI DUNG ASS ------------
# Hàm tạo header cho file ASS
function CreateAssHeader {
    $bs = $script:backslash
    $amp = $script:ampersand
    
    # Tạo từng phần riêng biệt
    $scriptInfo = @"
[Script Info]
; Script generated by basic-ass-creator.ps1
Title: Beautiful ASS Subtitle
ScriptType: v4.00+
Collisions: Normal
PlayResX: 1920
PlayResY: 1080
Timer: 100.0000
WrapStyle: 2
LineBreakStyle: 1
"@

    $stylesHeader = @"

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
"@

    # Tạo style riêng lẻ
    $defColorPrimary = "${amp}H00FFFFFF"
    $defColorSecondary = "${amp}H000000FF" 
    $defColorOutline = "${amp}H00000000"
    $defColorShadow = "${amp}H80000000"
    
    $defaultStyle = "Style: Default,Arial,32,$defColorPrimary,$defColorSecondary,$defColorOutline,$defColorShadow,-1,0,0,0,100,100,0,0,1,2.5,1.5,2,20,20,60,1"
    $titleStyle = "Style: Title,$script:titleFont,$script:titleFontSize,$defColorPrimary,$defColorSecondary,$defColorOutline,$defColorShadow,-1,0,0,0,100,100,0,0,1,3,2,8,10,10,10,1"
    
    $eventsHeader = @"

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"@

    # Kết hợp tất cả
    $header = $scriptInfo + $stylesHeader + "`n" + $defaultStyle + "`n" + $titleStyle + $eventsHeader
    return $header
}

# Hàm tạo dòng tiêu đề
function CreateTitleLine {
    param (
        [string]$style = $script:titleEffect
    )
    
    $bs = $script:backslash
    $amp = $script:ampersand
    
    # -------- THIẾT LẬP CÁC THAM SỐ HIỆU ỨNG THEO STYLE ---------
    switch ($style) {
        "minimal" {
            $rectWidth = 800
            $rectHeight = 120
            $cornerRadius = 10
            $glowWidth = 2
            $innerRectWidth = $rectWidth - 20
            $innerRectHeight = $rectHeight - 20
            $innerCornerRadius = $cornerRadius - 2
            $bgOpacity = "80"
            $blurAmount = 0.8
            $fadeTime = 800
            $transformScale = 105
        }
        "3d" {
            $rectWidth = 920
            $rectHeight = 180
            $cornerRadius = 10
            $glowWidth = 4
            $innerRectWidth = $rectWidth - 40
            $innerRectHeight = $rectHeight - 40
            $innerCornerRadius = $cornerRadius - 3
            $bgOpacity = "B0"
            $blurAmount = 2.0
            $fadeTime = 1200
            $transformScale = 110
        }
        default { # "modern"
            $rectWidth = 920
            $rectHeight = 180
            $cornerRadius = 20
            $glowWidth = 3
            $innerRectWidth = $rectWidth - 30
            $innerRectHeight = $rectHeight - 30
            $innerCornerRadius = $cornerRadius - 5
            $bgOpacity = $script:titleBgOpacity
            $blurAmount = 1.2
            $fadeTime = 1000
            $transformScale = 120
        }
    }
    
    # -------- TẠO HIỆU ỨNG CHO VĂN BẢN TIÊU ĐỀ ---------
    # Tạo tag fade với hiệu ứng fade in/out mượt mà
    $fadTag = "$bs" + "fad($fadeTime,$fadeTime)"
    
    # Tạo tag vị trí ở giữa màn hình
    $posTag = "$bs" + "pos(960,540)"
    
    # Tạo tag hiệu ứng gradient màu
    $colorTag1 = "$bs" + "1c$amp" + "H$script:titleColor1"
    $colorTag2 = "$bs" + "2c$amp" + "H$script:titleColor2"
    
    # Tạo tag viền và shadow
    $outlineTag = "$bs" + "3c$amp" + "H00000000" # Viền đen
    $blurTag = "$bs" + "blur$blurAmount" # Tăng blur cho vẻ hiện đại
    $borderTag = "$bs" + "bord2.5" # Viền mỏng hơn, hiện đại hơn
    $shadowTag = "$bs" + "shad1.5" # Bóng mỏng hơn
    
    # Tạo hiệu ứng transform hiện đại và mượt mà
    # Hiệu ứng xuất hiện từ không đến có với blur và scale
    $t1Start = "$bs" + "t(0,$fadeTime,$bs" + "fscx$transformScale$bs" + "fscy$transformScale$bs" + "blur5$bs" + "alpha&H30&)"
    # Hiệu ứng chuyển sang trạng thái ổn định
    $t2Mid = "$bs" + "t($fadeTime,$($fadeTime+1000),$bs" + "fscx100$bs" + "fscy100$bs" + "blur0.8$bs" + "alpha&H00&)"
    # Hiệu ứng nhẹ nhàng: phóng to nhẹ
    $t3Pulse1 = "$bs" + "t($($fadeTime+1000),$($fadeTime+2000),$bs" + "fscx103$bs" + "fscy103$bs" + "blur1.0)"
    # Hiệu ứng trở lại bình thường
    $t4Pulse2 = "$bs" + "t($($fadeTime+2000),$($fadeTime+3000),$bs" + "fscx100$bs" + "fscy100$bs" + "blur0.8)"
    # Hiệu ứng xoay nhẹ nhàng (góc nhỏ hơn)
    $t5Rotate = "$bs" + "t($($fadeTime+3000),$($fadeTime+4000),$bs" + "frz1$bs" + "fscx101)"
    # Hiệu ứng trở về ban đầu
    $t6Normal = "$bs" + "t($($fadeTime+4000),$($fadeTime+5000),$bs" + "frz0$bs" + "fscx100)"
    
    # Tạo tag phát sáng nhẹ nhàng
    $glowTag = "$bs" + "4a$amp" + "H40"
    
    # Tạo hiệu ứng rung nhẹ thanh lịch
    $orgTag = "$bs" + "org(960,540)"
    
    # Kết hợp các tag cho tiêu đề chính
    $allTags = "{$fadTag$posTag$orgTag$colorTag1$colorTag2$outlineTag$blurTag$borderTag$shadowTag$glowTag$t1Start$t2Mid$t3Pulse1$t4Pulse2$t5Rotate$t6Normal}"
    
    # Tạo dòng dialogue hoàn chỉnh với thời gian hiển thị
    $titleLine = "Dialogue: 0,0:00:00.00,0:00:0$script:titleDuration.00,Title,,0,0,0,,$allTags$script:titleText"
    
    # -------- TẠO HIỆU ỨNG MATERIAL DESIGN CHO NỀN ---------
    # Tạo hình chữ nhật bo tròn với hiệu ứng blur và gradient
    
    # Tạo nền mờ với hiệu ứng frosted glass kiểu iOS/Material Design
    $bgBlur = 8 # Độ blur cho nền
    $rectBgTag = "{$bs" + "an5$bs" + "pos(960,540)$bs" + "p1$bs" + "bord0$bs" + "shad0$bs" + "blur$bgBlur$bs" + "c$amp" + "H101820$bs" + "alpha&H$bgOpacity&$bs" + "fad($fadeTime,$fadeTime)}"
    
    # Tạo hình chữ nhật bo tròn với đường dẫn vector
    $rectPath = "m -$($rectWidth/2 - $cornerRadius) -$($rectHeight/2) " + # Bắt đầu từ trên trái (đã lùi vào cornerRadius)
                "l $($rectWidth - 2*$cornerRadius) 0 " + # Vẽ cạnh trên
                "b $cornerRadius 0 $cornerRadius 0 $cornerRadius $cornerRadius " + # Bo góc trên phải
                "l 0 $($rectHeight - 2*$cornerRadius) " + # Vẽ cạnh phải
                "b 0 $cornerRadius 0 $cornerRadius -$cornerRadius $cornerRadius " + # Bo góc dưới phải
                "l -$($rectWidth - 2*$cornerRadius) 0 " + # Vẽ cạnh dưới
                "b -$cornerRadius 0 -$cornerRadius 0 -$cornerRadius -$cornerRadius " + # Bo góc dưới trái
                "l 0 -$($rectHeight - 2*$cornerRadius) " + # Vẽ cạnh trái
                "b 0 -$cornerRadius 0 -$cornerRadius $cornerRadius -$cornerRadius" # Bo góc trên trái
                
    # Chọn layer dương thay vì âm nếu $script:useTitleLayers được thiết lập
    $rectBgLayer = if ($script:useTitleLayers) { 1 } else { -10 }            
    $rectBgLine = "Dialogue: $rectBgLayer,0:00:00.00,0:00:0$script:titleDuration.00,Title,,0,0,0,,$rectBgTag$rectPath"
    
    # Tạo viền phát sáng mờ xung quanh hình chữ nhật
    $rectGlowTag = "{$bs" + "an5$bs" + "pos(960,540)$bs" + "p1$bs" + "bord$glowWidth$bs" + "blur5$bs" + "c$amp" + "H$script:titleColor1$bs" + 
                   "3c$amp" + "H$script:titleColor2$bs" + "alpha&H90&$bs" + "fad($fadeTime,$fadeTime)$bs" + 
                   "t(0,3000,$bs" + "3c$amp" + "H$script:titleColor1$bs" + "c$amp" + "H$script:titleColor2$bs" + "alpha&H80&)$bs" + 
                   "t(3000,6000,$bs" + "3c$amp" + "H$script:titleColor2$bs" + "c$amp" + "H$script:titleColor1$bs" + "alpha&H90&)}"
    
    $rectGlowLayer = if ($script:useTitleLayers) { 2 } else { -9 }               
    $rectGlowLine = "Dialogue: $rectGlowLayer,0:00:00.00,0:00:0$script:titleDuration.00,Title,,0,0,0,,$rectGlowTag$rectPath"
    
    # Tạo hiệu ứng đường viền mảnh trang trí bên trong hình chữ nhật 
    $innerBorderWidth = 1 # Viền mảnh
    $innerRectTag = "{$bs" + "an5$bs" + "pos(960,540)$bs" + "p1$bs" + "bord$innerBorderWidth$bs" + "shad0$bs" + 
                    "c$amp" + "H$script:titleColor2$bs" + "3c$amp" + "H$script:titleColor1$bs" + 
                    "alpha&H60&$bs" + "fad($($fadeTime+200),$fadeTime)$bs" + 
                    "t(0,3000,$bs" + "3c$amp" + "H$script:titleColor2$bs" + "alpha&H50&)$bs" + 
                    "t(3000,6000,$bs" + "3c$amp" + "H$script:titleColor1$bs" + "alpha&H60&)}"
                    
    # Tạo đường dẫn tương tự cho hình chữ nhật bên trong
    $innerRectPath = "m -$($innerRectWidth/2 - $innerCornerRadius) -$($innerRectHeight/2) " +
                     "l $($innerRectWidth - 2*$innerCornerRadius) 0 " +
                     "b $innerCornerRadius 0 $innerCornerRadius 0 $innerCornerRadius $innerCornerRadius " +
                     "l 0 $($innerRectHeight - 2*$innerCornerRadius) " +
                     "b 0 $innerCornerRadius 0 $innerCornerRadius -$innerCornerRadius $innerCornerRadius " +
                     "l -$($innerRectWidth - 2*$innerCornerRadius) 0 " +
                     "b -$innerCornerRadius 0 -$innerCornerRadius 0 -$innerCornerRadius -$innerCornerRadius " +
                     "l 0 -$($innerRectHeight - 2*$innerCornerRadius) " +
                     "b 0 -$innerCornerRadius 0 -$innerCornerRadius $innerCornerRadius -$innerCornerRadius"
                     
    $innerBorderLayer = if ($script:useTitleLayers) { 3 } else { -8 }
    $innerBorderLine = "Dialogue: $innerBorderLayer,0:00:00.20,0:00:0$script:titleDuration.00,Title,,0,0,0,,$innerRectTag$innerRectPath"
    
    # -------- TẠO HIỆU ỨNG ÁNH SÁNG LƯỚT QUA ---------
    # Tạo hiệu ứng ánh sáng lướt qua tiêu đề (shine effect)
    $shineTag = "{$bs" + "an5$bs" + "pos(960,540)$bs" + "clip($bs" + "move(-300,-300,2220,1380,0,2000))$bs" + 
                "bord0$bs" + "shad0$bs" + "blur5$bs" + "c$amp" + "HFFFFFF$bs" + "alpha&H80&$bs" + 
                "t(0,2000,$bs" + "alpha&HB0&)}"
                
    $shineLayer = if ($script:useTitleLayers) { 4 } else { -5 }            
    $shineLine = "Dialogue: $shineLayer,0:00:01.00,0:00:03.00,Title,,0,0,0,,$shineTag$rectPath"
    
    # Thêm hiệu ứng ánh sáng thứ hai lướt qua theo hướng khác
    $shine2Tag = "{$bs" + "an5$bs" + "pos(960,540)$bs" + "clip($bs" + "move(2220,1380,-300,-300,0,1800))$bs" + 
                 "bord0$bs" + "shad0$bs" + "blur5$bs" + "c$amp" + "HFFFFFF$bs" + "alpha&H90&$bs" + 
                 "t(0,1800,$bs" + "alpha&HB0&)}"
                 
    $shine2Layer = if ($script:useTitleLayers) { 4 } else { -5 }             
    $shine2Line = "Dialogue: $shine2Layer,0:00:03.50,0:00:05.50,Title,,0,0,0,,$shine2Tag$rectPath"
    
    # -------- TẠO HIỆU ỨNG CHI TIẾT BỔ SUNG XUNG QUANH ---------
    # Thêm các chi tiết trang trí ở góc
    $decorSize = 40 # Kích thước các chi tiết trang trí 
    
    # Góc trên trái
    $decorTLTag = "{$bs" + "pos($($960-$rectWidth/2+$cornerRadius), $($540-$rectHeight/2+$cornerRadius))$bs" + 
                  "an7$bs" + "p1$bs" + "bord0$bs" + "shad0$bs" + "blur0.8$bs" + 
                  "c$amp" + "H$script:titleColor1$bs" + "alpha&H40&$bs" + "fad($fadeTime,$fadeTime)}"
    $decorTLPath = "m 0 0 l $decorSize 0 l 0 $decorSize"
    
    $decorLayer = if ($script:useTitleLayers) { 5 } else { -6 }
    $decorTLLine = "Dialogue: $decorLayer,0:00:00.30,0:00:0$script:titleDuration.00,Title,,0,0,0,,$decorTLTag$decorTLPath"
    
    # Góc trên phải
    $decorTRTag = "{$bs" + "pos($($960+$rectWidth/2-$cornerRadius), $($540-$rectHeight/2+$cornerRadius))$bs" + 
                  "an9$bs" + "p1$bs" + "bord0$bs" + "shad0$bs" + "blur0.8$bs" + 
                  "c$amp" + "H$script:titleColor2$bs" + "alpha&H40&$bs" + "fad($fadeTime,$fadeTime)}"
    $decorTRPath = "m 0 0 l -$decorSize 0 l 0 $decorSize"
    $decorTRLine = "Dialogue: $decorLayer,0:00:00.50,0:00:0$script:titleDuration.00,Title,,0,0,0,,$decorTRTag$decorTRPath"
    
    # Góc dưới trái
    $decorBLTag = "{$bs" + "pos($($960-$rectWidth/2+$cornerRadius), $($540+$rectHeight/2-$cornerRadius))$bs" + 
                  "an1$bs" + "p1$bs" + "bord0$bs" + "shad0$bs" + "blur0.8$bs" + 
                  "c$amp" + "H$script:titleColor2$bs" + "alpha&H40&$bs" + "fad($fadeTime,$fadeTime)}"
    $decorBLPath = "m 0 0 l $decorSize 0 l 0 -$decorSize"
    $decorBLLine = "Dialogue: $decorLayer,0:00:00.70,0:00:0$script:titleDuration.00,Title,,0,0,0,,$decorBLTag$decorBLPath"
    
    # Góc dưới phải
    $decorBRTag = "{$bs" + "pos($($960+$rectWidth/2-$cornerRadius), $($540+$rectHeight/2-$cornerRadius))$bs" + 
                  "an3$bs" + "p1$bs" + "bord0$bs" + "shad0$bs" + "blur0.8$bs" + 
                  "c$amp" + "H$script:titleColor1$bs" + "alpha&H40&$bs" + "fad($fadeTime,$fadeTime)}"
    $decorBRPath = "m 0 0 l -$decorSize 0 l 0 -$decorSize"
    $decorBRLine = "Dialogue: $decorLayer,0:00:00.90,0:00:0$script:titleDuration.00,Title,,0,0,0,,$decorBRTag$decorBRPath"
    
    # -------- TẠO THÊM HIỆU ỨNG PARTICLE CHO PHONG CÁCH HIỆN ĐẠI ---------
    if ($style -eq "modern" -or $style -eq "3d") {
        # Hiệu ứng hạt nhỏ bay xung quanh tiêu đề
        $particleCount = 6
        $particleLines = ""
        
        for ($i = 1; $i -le $particleCount; $i++) {
            $delay = 0.3 * $i
            $size = 5 + (Get-Random -Minimum 3 -Maximum 15)
            $xOffset = Get-Random -Minimum -500 -Maximum 500
            $yOffset = Get-Random -Minimum -300 -Maximum 300
            $moveDuration = Get-Random -Minimum 2000 -Maximum 4000
            $opacity = 50 + (Get-Random -Minimum 20 -Maximum 40)
            
            $particleTag = "{$bs" + "pos($($960+$xOffset),$($540+$yOffset))$bs" + "an5$bs" + "p1$bs" + 
                          "bord0$bs" + "shad0$bs" + "blur3$bs" + 
                          "c$amp" + "H$(if ($i % 2 -eq 0) { $script:titleColor1 } else { $script:titleColor2 })$bs" + 
                          "alpha&H$($opacity.ToString('X2'))&$bs" + "fad(800,800)$bs" + 
                          "t(0,$moveDuration,$bs" + "alpha&HB0&$bs" + "move($($960+$xOffset),$($540+$yOffset),$($960+$xOffset/2),$($540+$yOffset/2)))}"
            
            $particlePath = "m -$($size/2) -$($size/2) l $size 0 l 0 $size l -$size 0 l 0 -$size"
            
            $particleLayer = if ($script:useTitleLayers) { 6 } else { -7 }
            $particleLine = "Dialogue: $particleLayer,0:00:0$($delay).00,0:00:0$($script:titleDuration-1).00,Title,,0,0,0,,$particleTag$particlePath"
            $particleLines += "`n" + $particleLine
        }
    } else {
        $particleLines = ""
    }
    
    # -------- KẾT HỢP TẤT CẢ CÁC HIỆU ỨNG ---------
    # Đảm bảo layer tiêu đề chính cao hơn tất cả các hiệu ứng
    $titleLayer = if ($script:useTitleLayers) { 10 } else { 0 }
    $titleLine = "Dialogue: $titleLayer,0:00:00.00,0:00:0$script:titleDuration.00,Title,,0,0,0,,$allTags$script:titleText"
    
    return $rectBgLine + "`n" + $rectGlowLine + "`n" + $innerBorderLine + "`n" + 
           $decorTLLine + "`n" + $decorTRLine + "`n" + $decorBLLine + "`n" + $decorBRLine + "`n" + 
           $shineLine + "`n" + $shine2Line + "`n" + $particleLines + "`n" + $titleLine
}

# Hàm tạo dòng dialogue với hiệu ứng highlight từng từ
function CreateHighlightDialogueLine2 {
    param (
        [double]$startTime,
        [double]$endTime,
        [PSCustomObject[]]$wordObjects
    )
    
    # Kiểm tra số lượng từ, bỏ qua nếu chỉ có 1 từ
    if ($wordObjects.Length -lt $script:minWordCount) {
        return ""
    }
    
    $bs = $script:backslash
    $amp = $script:ampersand
    
    # Định dạng thời gian bắt đầu và kết thúc
    $startTimeAss = FormatAssTime $startTime
    $endTimeAss = FormatAssTime $endTime
    
    # Tạo tag fade đẹp hơn với thời gian fade in/out
    $fadeTag = "$bs" + "fad(200,200)"
    
    # Tạo các tag hiệu ứng cơ bản
    $blurTag = "$bs" + "blur0.6"
    $borderTag = "$bs" + "bord1.8"
    $shadowTag = "$bs" + "shad1.2"
    $spacingTag = "$bs" + "fsp0.5"
    
    # Tạo tag hiệu ứng cơ bản
    $basicEffect = "{$fadeTag$blurTag$borderTag$shadowTag$spacingTag}"
    
    # Tạo tag màu mặc định và highlight
    $defaultColorTag = "$bs" + "c$amp" + "H$script:defaultColor"
    $highlightColorTag = "$bs" + "c$amp" + "H$script:highlightColor"
    $outlineTag = "$bs" + "3c$amp" + "H$script:outlineColor"
    $shadowColorTag = "$bs" + "4c$amp" + "H$script:shadowColor"
    
    # Xây dựng chuỗi phụ đề với hiệu ứng highlight
    $dialogueLines = @()
    
    # Tạo một dòng phụ đề với màu mặc định cho tất cả các từ (layer 0)
    $defaultText = "{$defaultColorTag$outlineTag$shadowColorTag}"
    $fullText = ""
    foreach ($wordObj in $wordObjects) {
        $fullText += "$($wordObj.word) "
    }
    $fullText = $fullText.TrimEnd()
    
    # Xử lý chia văn bản thành tối đa 2 dòng
    $words = $fullText.Split(' ')
    $formattedText = ""
    $currentLine = ""
    $lineCount = 0
    
    # Tính toán tổng số ký tự và phân phối đều cho 2 dòng
    $totalChars = $fullText.Length
    $idealCharsPerLine = [Math]::Ceiling($totalChars / $script:maxSubtitleLines)
    $effectiveMaxChars = [Math]::Min($script:maxCharsPerLine, [Math]::Max($idealCharsPerLine, 20))
    
    # Đảm bảo luôn có 2 dòng phụ đề nếu văn bản đủ dài
    $forceNewLine = $totalChars -gt 30 -and $words.Length -gt 3
    
    # Xử lý trường hợp có từ quá dài
    $longWordThreshold = 20
    $processedWords = @()
    foreach ($word in $words) {
        if ($word.Length -gt $longWordThreshold) {
            # Chia từ dài thành các phần nhỏ hơn
            $parts = [System.Collections.ArrayList]::new()
            for ($i = 0; $i -lt $word.Length; $i += $longWordThreshold) {
                $length = [Math]::Min($longWordThreshold, $word.Length - $i)
                $parts.Add($word.Substring($i, $length)) | Out-Null
            }
            $processedWords += $parts
        } else {
            $processedWords += $word
        }
    }
    $words = $processedWords
    
    foreach ($word in $words) {
        # Nếu đã có đủ số dòng tối đa, thêm từ vào dòng cuối
        if ($lineCount -ge ($script:maxSubtitleLines - 1)) {
            if ($currentLine.Length -gt 0) {
                $currentLine += " "
            }
            $currentLine += $word
        }
        # Nếu thêm từ này vào dòng hiện tại sẽ vượt quá giới hạn, tạo dòng mới
        elseif (($currentLine.Length + $word.Length + 1) -gt $effectiveMaxChars -or 
               ($forceNewLine -and $lineCount -eq 0 -and $currentLine.Length -gt ($totalChars / 2))) {
            $formattedText += $currentLine
            $currentLine = $word
            $lineCount++
            
            # Thêm ký tự ngắt dòng
            if ($lineCount -lt $script:maxSubtitleLines) {
                $formattedText += "$bs" + "N"
            }
        } 
        # Thêm từ vào dòng hiện tại
        else {
            if ($currentLine.Length -gt 0) {
                $currentLine += " "
            }
            $currentLine += $word
        }
    }
    
    # Thêm dòng cuối cùng vào văn bản đã định dạng
    if ($currentLine.Length -gt 0) {
        # Nếu chưa có dòng nào, thêm trực tiếp
        if ($formattedText.Length -eq 0) {
            $formattedText = $currentLine
        }
        # Nếu đã có dòng và chưa đạt số dòng tối đa, thêm ngắt dòng
        elseif ($lineCount -lt ($script:maxSubtitleLines - 1)) {
            $formattedText += "$bs" + "N" + $currentLine
        }
        # Nếu không, nối vào dòng cuối cùng
        else {
            $formattedText += $currentLine
        }
    }
    
    # Thêm dòng phụ đề mặc định (layer 0)
    $dialoguePrefix = "Dialogue: 0,$startTimeAss,$endTimeAss,Default,,0,0,0,," 
    $dialogueLines += $dialoguePrefix + $basicEffect + $defaultText + $formattedText
    
    # Tạo các dòng phụ đề highlight cho từng từ (layer 1) - không có hiệu ứng nhảy
    foreach ($wordObj in $wordObjects) {
        $wordStart = $wordObj.start
        $wordEnd = $wordObj.end
        
        # Chỉ tạo highlight nếu từ nằm trong khoảng thời gian của đoạn
        if (($wordStart -ge $startTime) -and ($wordEnd -le $endTime)) {
            # Định dạng thời gian bắt đầu và kết thúc cho từng từ
            $wordStartAss = FormatAssTime $wordStart
            $wordEndAss = FormatAssTime $wordEnd
            
            # Tạo hiệu ứng glow cho từ được highlight
            $glowTag = "$bs" + "4a$amp" + "H30"
            
            # Tạo văn bản với từ được highlight - không có hiệu ứng transform để tránh nhảy
            $highlightText = "{$defaultColorTag$outlineTag$shadowColorTag}"
            
            # Tạo văn bản highlight với cùng định dạng dòng như văn bản gốc
            $words = $formattedText.Split("$bs" + "N")
            $highlightFormattedText = ""
            
            for ($lineIdx = 0; $lineIdx -lt $words.Length; $lineIdx++) {
                $line = $words[$lineIdx]
                $lineWords = $line.Split(' ')
                $highlightLine = ""
                
                foreach ($lineWord in $lineWords) {
                    if ($lineWord -eq $wordObj.word) {
                        $highlightLine += "{$highlightColorTag$glowTag}$lineWord{$defaultColorTag} "
                    } else {
                        $highlightLine += "$lineWord "
                    }
                }
                
                $highlightFormattedText += $highlightLine.TrimEnd()
                
                # Thêm ngắt dòng nếu không phải dòng cuối
                if ($lineIdx -lt $words.Length - 1) {
                    $highlightFormattedText += "$bs" + "N"
                }
            }
            
            # Thêm dòng highlight cho từ này (layer 1)
            $highlightPrefix = "Dialogue: 1,$wordStartAss,$wordEndAss,Default,,0,0,0,," 
            $highlightEffect = "{$blurTag$borderTag$shadowTag$spacingTag}"
            $dialogueLines += $highlightPrefix + $highlightEffect + $highlightText + $highlightFormattedText
        }
    }
    
    return $dialogueLines -join "`n"
}

# Hàm chuyển đổi JSON thành ASS
function ConvertJsonToAss {
    param (
        [string]$whisperJsonPath,
        [string]$outputJsonPath,
        [string]$assFilePath = "subtitle.ass"
    )
    
    # Kiểm tra file JSON có tồn tại không
    if (-not (Test-Path $whisperJsonPath)) {
        Write-Error "File $whisperJsonPath không tồn tại."
        return $false
    }
    
    if (-not (Test-Path $outputJsonPath)) {
        Write-Error "File $outputJsonPath không tồn tại."
        return $false
    }
    
    try {
        # Đọc dữ liệu từ file JSON
        $whisperData = Get-Content -Path $whisperJsonPath -Raw -Encoding UTF8 | ConvertFrom-Json
        $outputData = Get-Content -Path $outputJsonPath -Raw -Encoding UTF8 | ConvertFrom-Json
        
        # Tạo header cho file ASS (bỏ phần tiêu đề)
        $assHeader = CreateAssHeader
        # Loại bỏ dòng tiêu đề để không hiển thị hiệu ứng nháy ở giữa màn hình
        $assContent = $assHeader
        
        # Lấy dữ liệu từ whisper
        $transcription = $whisperData[0]
        $allWords = $transcription.words
        
        # Lấy dữ liệu từ output.json
        $groups = $outputData[0].groups
        
        # Xử lý từng nhóm phụ đề
        foreach ($group in $groups) {
            $startTime = $group.start
            $endTime = $group.end
            $startIndex = $group.startIndex
            $endIndex = $group.endIndex
            
            # Lấy các từ trong nhóm này từ whisper data
            $groupWords = $allWords[$startIndex..$endIndex]
            
            # Bỏ qua nhóm chỉ có 1 từ
            if ($groupWords.Length -lt $script:minWordCount) {
                Write-Host "Bỏ qua phụ đề chỉ có $($groupWords.Length) từ: $($groupWords[0].word)"
                continue
            }
            
            # Tạo hiệu ứng highlight cho nhóm từ này (sử dụng phương pháp thay thế)
            $dialogueLine = CreateHighlightDialogueLine2 $startTime $endTime $groupWords
            if ($dialogueLine -ne "") {
                $assContent += "`n" + $dialogueLine
            }
        }
        
        # Ghi nội dung ASS vào file
        $assContent | Out-File -FilePath $assFilePath -Encoding UTF8
        Write-Host "Đã tạo thành công file phụ đề ASS: $assFilePath"
        
        return $true
    }
    catch {
        Write-Error "Lỗi khi chuyển đổi file: $_"
        return $false
    }
}

# ------------ THỰC THI CHƯƠNG TRÌNH ------------
# Xác định đường dẫn file đầu vào và đầu ra
$whisperJsonFile = if ($args.Count -gt 0) { $args[0] } else { "whisper-transcription.json" }
$outputJsonFile = if ($args.Count -gt 1) { $args[1] } else { "output.json" }
$assFile = if ($args.Count -gt 2) { $args[2] } else { "subtitle.ass" }

# Chạy chương trình chuyển đổi
Write-Host "Bắt đầu chuyển đổi từ $whisperJsonFile và $outputJsonFile sang $assFile..."
$result = ConvertJsonToAss -whisperJsonPath $whisperJsonFile -outputJsonPath $outputJsonFile -assFilePath $assFile

# Kiểm tra kết quả
if (-not $result) {
    Write-Host "Chuyển đổi không thành công." -ForegroundColor Red
    exit 1
} else {
    Write-Host "Chuyển đổi thành công! File ASS đã được tạo với hiệu ứng highlight từng từ." -ForegroundColor Green
}
